In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model = Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
model.get_weights()

[array([[ 0.31677222, -0.66141593],
        [ 0.7687719 ,  0.50266993]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7157654],
        [ 0.5254687]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [8]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 2s 12ms/step - loss: 0.7479
Epoch 2/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7469
Epoch 3/50
4/4 [==============================] - 0s 6ms/step - loss: 0.7471
Epoch 4/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7457
Epoch 5/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7448
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.7449
Epoch 7/50
4/4 [==============================] - 0s 6ms/step - loss: 0.7438
Epoch 8/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7431
Epoch 9/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7423
Epoch 10/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7417
Epoch 11/50
4/4 [==============================] - 0s 6ms/step - loss: 0.7410
Epoch 12/50
4/4 [==============================] - 0s 7ms/step - loss: 0.7404
Epoch 13/50
4/4 [==============================] - 0s 8ms/step - loss: 0