In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.get_weights()

[array([[-0.2821104,  1.1063989],
        [-0.0949657, -0.8214803]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7449728],
        [ 0.3057406]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [10]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 2s 10ms/step - loss: 15.8963
Epoch 2/75
4/4 [==============================] - 0s 7ms/step - loss: 9.8551
Epoch 3/75
4/4 [==============================] - 0s 7ms/step - loss: 7.5731
Epoch 4/75
4/4 [==============================] - 0s 8ms/step - loss: 4.4223
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 4.1948
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 2.8891
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 2.8026
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 2.7239
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 2.5519
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 2.4490
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 2.1067
Epoch 12/75
4/4 [==============================] - 0s 5ms/step - loss: 1.9123
Epoch 13/75
4/4 [==============================] - 0s 5ms/step - loss: 

In [11]:
model.get_weights()

[array([[-0.3259644 ,  1.3021204 ],
        [-0.40777785, -0.68940085]], dtype=float32),
 array([-0.20480494,  0.15432476], dtype=float32),
 array([[-0.9530147],
        [-0.358528 ]], dtype=float32),
 array([0.20274955], dtype=float32)]